# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\"&\n\x13NotificationRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x14NotificationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32X\n\x13NotificationService\x12\x41\n\x10SendNotification\x12\x14.NotificationRequest\x1a\x15.NotificationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFICATIONREQUEST']._serialized_start=22
  _globals['_NOTIFICATIONREQUEST']._serialized_end=60
  _globals['_NOTIFICATIONRESPONSE']._serialized_start=62
  _globals['_NOTIFICATIONRESPONSE']._serialized_end=101
  _globals['_NOTIFICATIONSERVICE']._serialized_start=103
  _globals['_NOTIFICATIONSERVICE']._serialized_end=191
# @@protoc_insertion_point(module_scope)
